### ISSUE TITLE
Termination cheking error

### ISSUE THREAD

**Issue by asr** [cj-xu/OrdinalNotations#1]
I'm getting the following error using the current master (89985ac4b7d601a192b438f097a8bcb1494e994b):

```
$ agda index.lagda
...
Termination checking failed for the following functions:
  to, to-<, to-≥
Problematic calls:
  to-≥ r
  to (O.fst O.ω^ b + c [ _ ])
  to O.𝟎
  to-< p
    (at /tmp/OrdinalNotations/src/OrdinalNotationsWithoutRecursion.lagda:132,59-63)
when scope checking the declaration
  import OrdinalNotationsWithoutRecursion
/tmp/OrdinalNotations/src/OrdinalNotationsWithoutRecursion.lagda:171,28-32
to (from 𝟎) != 𝟎 of type 𝒪
when checking that the expression refl has type to (from 𝟎) ≡ 𝟎
```

Versions: Agda 2.6.0 and standard library 1.0

**Comment by fredrikNordvallForsberg** [comment]
To do: make a smaller standalone example, and submit an Agda bug report. Basically the problem was a (obviously smaller) recursive call in an implicit argument (to a constructor): if inferred by Agda, there is a problem with termination, but if given explicitly, everything is fine.

**Comment by fredrikNordvallForsberg** [comment]
And thanks @asr for pointing out the problem! The old code worked on a previous version of Agda master, so I'll try to find a self-contained example as a bug report.

**Comment by asr** [comment]
So, it seems the error in 2.6.0 is a regression. Please try to find the MWE and report the issue.
